name: scopus
channels:
  - conda-forge
dependencies:
  - awesome-slugify=1.6.5
  - nbconvert=6.1.0
  - notebook=6.4.3
  - numpy=1.21.1
  - openpyxl=3.0.7
  - pandas=1.3.1
  - python=3.9.6
  - requests=2.26.0
  - xlrd=2.0.1
